import Head from "next/head";
import styles from "../styles/Home.module.css";
import { useState } from "react";

export default function Home() {
	const [directions, setDirections] = useState("");
	const [list, setList] = useState([]);
	return (
		<div className={styles.container}>
			<Head>
				<title>Chat </title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className={styles.main}>
				<h1 className={styles.title}>Fun With AI!</h1>
			</main>
		</div>
	);
}
